version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.9
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.2.1
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.7.1
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.0
    - 2.8.0
  - dependency-name: gatsby-remark-katex
    versions:
    - 3.9.0
  - dependency-name: gatsby-plugin-feed
    versions:
    - 2.12.0
  - dependency-name: gatsby-remark-autolink-headers
    versions:
    - 2.10.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
