backend:
  name: git-gateway
  branch: master

media_folder: 'static/media'
public_folder: '/media'

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template',
          name: 'template',
          widget: 'hidden',
          default: 'post',
        }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - {
          label: 'Brouillon ?',
          name: 'draft',
          widget: 'boolean',
          default: true,
        }
      - { label: 'Date du voyage', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Catégorie', name: 'category', widget: 'string' }
      - { label: 'Texte', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Pays', name: 'country', widget: 'string' }
      - { label: 'Ville(s)', name: 'city', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template',
          name: 'template',
          widget: 'hidden',
          default: 'page',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
